"""
Django settings for ShadeStore project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nuzrq^fda#bx7^2-njw1e^niom61w&+cm&63g7t_fn*mbljxca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecom',
    'Showroom_staff',
    'painter',
    'chat',
    #'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ecom.middleware.RoleBasedRedirectMiddleware',
    
    
]
 # Save the session on every request

ROOT_URLCONF = 'ShadeStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecom.context_processors.categories_processor',
               
            ],
        },
    },
]

WSGI_APPLICATION = 'ShadeStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR/ "static",
]
MEDIA_URL='/images/'
MEDIA_ROOT=BASE_DIR/'static'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 # Redirect after login
LOGOUT_REDIRECT_URL = 'index' 
# Jazzmin settings
JAZZMIN_SETTINGS = {
    # Title of the window
    "site_title": "ShadeStore Admin",
    
    # Title on the login screen (split into two lines)
    "site_header": "ShadeStore Admin",
    
    # Title on the brand (split into two lines)
    "site_brand": "ShadeStore \n Admin",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to ShadeStore Admin Panel",
    
    # Copyright on the footer
    "copyright": "ShadeStore Ltd",
    
    # The model admin to search from the search bar
    "search_model": "auth.User",
    
    # Remove logo
    "site_logo": None,
    
    # CSS theme to use
    "theme": "default",
    
    # Default UI tweaks
    "show_ui_builder": True,
    
    # Change view format
    "changeform_format": "horizontal_tabs",
    
    # Navigation expanded
    "navigation_expanded": True,
    
    # Custom icons for your models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "ecom.tbl_product": "fas fa-paint-brush",
        "ecom.tbl_category": "fas fa-tag",
        "ecom.PainterBooking": "fas fa-calendar",
        "ecom.Painter": "fas fa-user-hard-hat",
        "ecom.Cart": "fas fa-shopping-cart",
    },
    
    # Custom links to add to the nav menu
    "custom_links": {
        "ecom": [{
            "name": "View Website",
            "url": "/",  # Your site's homepage URL
            "icon": "fas fa-globe",
        }],
    },
}

# UI tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-danger",
    "accent": "accent-maroon",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "litera",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True
}


RAZORPAY_KEY_ID = 'rzp_test_CItsIabNLe0DJK'
RAZORPAY_KEY_SECRET = 'j0N43ExAXldX3tyJvCfPXr8p'
GOOGLE_MAPS_API_KEY = 'AIzaSyA7xDfeG7J9X3HrYdbKcD_uqNDKUsqsBh8'

# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'amalmanoj396@gmail.com'  # your Gmail address
EMAIL_HOST_PASSWORD = 'krkjxhhsizqiypei '  # not your Gmail password
DEFAULT_FROM_EMAIL = 'amalmanoj396@gmail.com'
ADMIN_EMAIL = 'amalmanoj396@gmail.com'  # or your Gmail again if it's the same
