# Generated by Django 5.1.5 on 2025-02-09 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('category_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('approched_by_staff', models.BooleanField(default=False)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_area', models.CharField(max_length=255)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incentive_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('join_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldstaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('join_date', models.CharField(max_length=255, unique=True)),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('onproject', 'On Project'), ('unavailable', 'Unavailable')], default='available', max_length=12)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShowroomStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('join_date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('price', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('large_project', models.BooleanField(default=False)),
                ('site_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('square_feet', models.IntegerField()),
                ('stage_of_construction', models.CharField(choices=[('foundation', 'Foundation'), ('middle', 'Middle'), ('final', 'Final')], max_length=10)),
                ('proposed_date_visit', models.DateField()),
                ('field_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='ecom.fieldstaff')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('additional_image_1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('additional_image_2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('additional_image_3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ecom.tbl_category')),
            ],
        ),
    ]
