# Generated by Django 5.1.5 on 2025-02-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
