# Generated by Django 5.1.5 on 2025-02-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_alter_sitevisit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='price',
        ),
    ]
