# Generated by Django 5.1.5 on 2025-02-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_remove_sitevisit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='owner_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
