# Generated by Django 5.1.5 on 2025-03-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_sitevisit_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='available_colors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
