# Generated by Django 5.1.5 on 2025-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_tbl_product_available_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='available_colors',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='available_shades',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
