# Generated by Django 5.1.5 on 2025-03-13 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_alter_painter_salary_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PainterBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completion_date', models.DateField()),
                ('square_feet', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painter_bookings', to=settings.AUTH_USER_MODEL)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.painter')),
            ],
        ),
    ]
