# Generated by Django 5.1.5 on 2025-03-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_order_customer_order_date_order_field_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_delivery',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
