# Generated by Django 5.1.5 on 2025-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_customer_staff_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_category',
            name='quantity_calculation_method',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('shade_based', 'Shade-Based'), ('custom', 'Custom Calculation')], default='manual', max_length=20),
        ),
    ]
