# Generated by Django 5.1.5 on 2025-03-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_painterbooking_order_alter_order_status_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approached_customers', to='ecom.fieldstaff'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
