# Generated by Django 5.1.5 on 2025-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_alter_customer_staff_member_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'shipped'), ('completed', 'completed'), ('delivered', 'delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
