# Generated by Django 5.1.5 on 2025-03-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_order_delivery_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='painterbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
