# Generated by Django 5.1.5 on 2025-04-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painterbooking',
            name='notes',
        ),
        migrations.AlterField(
            model_name='customer',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approached_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
