# Generated by Django 5.1.5 on 2025-04-05 08:17

import django.db.models.deletion
import ecom.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_tbl_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbl_review',
            options={'ordering': ['-verified_purchase', '-helpful_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=ecom.models.tbl_review.review_image_path),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=ecom.models.tbl_review.review_image_path),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=ecom.models.tbl_review.review_image_path),
        ),
        migrations.AddField(
            model_name='tbl_review',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_marks', to='ecom.tbl_review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('review', 'user')},
            },
        ),
    ]
