# Generated by Django 5.1.5 on 2025-04-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0023_alter_tbl_review_options_tbl_review_helpful_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_delivery',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
