# Generated by Django 5.1.5 on 2025-05-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0025_alter_order_status_alter_painterbooking_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldstaff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
