# Generated by Django 5.1.5 on 2025-05-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_fieldstaff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroomstaff',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
