# Generated by Django 5.1.5 on 2025-05-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_showroomstaff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='painter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
