# Generated by Django 5.1.5 on 2025-04-14 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_attachments/images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('none', 'None'), ('file', 'File'), ('image', 'Image'), ('location', 'Location')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='original_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='chat.message'),
        ),
    ]
